<?php

module_load_include('inc', 'castleschool', 'functions');
module_load_include('inc', 'castleschool', 'forms');

/**
 * Implements hook_permission().
 */
function castleschool_permission() {
  return array(
    'Modify Castle School settings' =>  array(
      'title' => t('Modify Castle School settings'),
      'description' => t('Administer Castle School settings.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function castleschool_menu() {

  $items = array();

  $items['choose-your-accommodation/%'] = array(
    'page callback' => 'castleschool_accommodation_selected',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['castleschool/quote/%/%/%'] = array(
    'page callback' => 'castleschool_get_quote',
    'type' => MENU_CALLBACK,
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access content'),
  );

  $items['castleschool/accommodation-quote/%'] = array(
    'page callback' => 'castleschool_get_accommodation_quote',
    'type' => MENU_CALLBACK,
    'page arguments' => array(2),
    'access arguments' => array('access content'),
  );

  $items['castleschool/extras-quote/%/%'] = array(
    'page callback' => 'castleschool_get_extras_quote',
    'type' => MENU_CALLBACK,
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
  );

  $items['castleschool/summary-quote-total/%/%/%'] = array(
    'page callback' => 'castleschool_get_summary_quote_total',
    'type' => MENU_CALLBACK,
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access content'),
  );

  $items['admin/settings/castleschool'] = array(
    'title' => 'Castle School',
    'description' => 'Castle School module settings control',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('castleschool_admin'),
    'access arguments' => array('Modify Castle School settings'),
    'type' => MENU_NORMAL_ITEM
  );

  $items['admin/settings/castleschool/choosecourse'] = array(
    'title' => 'Choose Your Course Form',
    'description' => 'Settings for Choose Your Course Form.',
    'page callback' => '', // 'uc_store_reports',
    'access arguments' => array('Modify Castle School settings'),
    'weight' => 2,
    'file' => '', // 'uc_store.admin.inc',
    'position' => 'right',
  );

  return $items;
}

/**
 * Implements hook_admin().
 */
function castleschool_admin() {

  $form['general'] = array(
    '#type' => 'fieldset',
    '#title' => t('General Configuration'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function castleschool_block_info() {

  return array(
    'castleschool_teaser' => array(
      'info' => t('Castle School Quote Teaser Form'),
    ),
    'castleschool_choose_course' => array(
      'info' => t('Castle School Choose Your Course Form'),
    ),
    'castleschool_search_accomm' => array(
      'info' => t('Castle School Search For Accommodation Form'),
    ),
    'castleschool_choose_accomm' => array(
      'info' => t('Castle School Choose Accommodation Form'),
    ),
    'castleschool_airport_transfers' => array(
      'info' => t('Castle School Airport Transfers Form'),
    ),
    'castleschool_finalquote' => array(
      'info' => t('Castle School Final Quote'),
    ),
    'castleschool_booking_form' => array(
      'info' => t('Castle School Booking Form'),
    ),
    'castleschool_quotesummary' => array(
      'info' => t('Castle School Quote Summary'),
    )
  );
}

/**
 * Implements hook_block_configure().
 */
function castleschool_block_configure($delta='') {
  $form = array();

  switch($delta) {
    case 'castleschool_teaser' :
      break;
    case 'castleschool_choose_course' :
      break;
    case 'castleschool_search_accomm' :
      break;
    case 'castleschool_choose_accomm' :
      break;
    case 'castleschool_airport_transfers' :
      break;
    case 'castleschool_finalquote' :
      break;
    case 'castleschool_booking_form' :
      break;
    case 'castleschool_quotesummary' :
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function castleschool_block_save($delta = '', $edit = array()) {

  switch($delta) {
    case 'castleschool_teaser' :
      break;
    case 'castleschool_choose_course' :
      break;
    case 'castleschool_search_accomm' :
      break;
    case 'castleschool_choose_accomm' :
      break;
    case 'castleschool_airport_transfers' :
      break;
    case 'castleschool_finalquote' :
      break;
    case 'castleschool_booking_form' :
      break;
    case 'castleschool_quotesummary' :
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function castleschool_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'castleschool_teaser' :
      $weeks = array();
      for ($i = 2; $i <= 52; $i++) {
        $weeks[$i] = $i . t(' weeks');
      }
      $node = menu_get_object();
      $block['content'] = array(
        drupal_get_form('castleschool_teaser_form', $weeks),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/teaser.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/teaser.js',
          ),
        ),
      );
      break;
    case 'castleschool_choose_course' :
      $weeks = array();
      for ($i = 2; $i <= 52; $i++) {
        $weeks[$i] = $i . t(' weeks');
      }
      $block['content'] = array(
        drupal_get_form('castleschool_choose_course_form', $weeks),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/choose-your-course.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/choose-your-course.js',
          ),
        ),
      );
      break;
    case 'castleschool_search_accomm' :
      $weeks = array();
      for ($i = $_SESSION['castleschool_weeks']; $i >= 2; $i--) {
        $weeks[$i] = $i . t(' weeks');
      }
      $block['content'] = array(
        drupal_get_form('castleschool_search_for_accommodation_form', $weeks),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/search-for-accommodation.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/search-for-accommodation.js',
          ),
        ),
      );
      break;
    case 'castleschool_choose_accomm' :
      $block['content'] = array(
        drupal_get_form('castleschool_choose_accommodation_form'),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/choose-accommodation.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/choose-accommodation.js',
          ),
        ),
      );
      break;
    case 'castleschool_airport_transfers' :
      $block['content'] = array(
        drupal_get_form('castleschool_airport_transfers_form'),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/airport-transfers.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/airport-transfers.js',
          ),
        ),
      );
      break;
    case 'castleschool_finalquote' :
      $block['content'] = array(
        drupal_get_form('castleschool_finalquote_form'),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/your-quote.css',
          ),
        ),
      );
      break;
    case 'castleschool_booking_form' :
      $block['content'] = array(
        drupal_get_form('castleschool_bookingform_form'),
      );
      break;
    case 'castleschool_quotesummary' :
      $block['content'] = array(
        '#markup' => castleschool_quotesummary_content(),
      );
      $path = drupal_get_path('module', 'castleschool');
      $block['content']['#attached'] = array(
        'css' => array(
          array(
            'type' => 'file',
            'data' => $path . '/css/quote-summary.css',
          ),
        ),
        'js' => array(
          array(
            'type' => 'file',
            'data' => $path . '/js/quote-summary.js',
          ),
        ),
      );
      break;
  }

  return $block;
}
